version: "3"
# Other docker-compose examples in /examples

services:
  minecraft:
    image: itzg/minecraft-server:adopt11
    ports:
      - "25565:25565"
    volumes:
      - "./server:/data"
      - "./target/Skyish-1.0-SNAPSHOT.jar:/data/plugins/Skyish-1.0-SNAPSHOT.jar"
    environment:
      EULA: "TRUE"
      TYPE: "SPIGOT"
      VERSION: "1.16.4"
    restart: always

volumes:
  mc: {}
